name: DeaDBeeF plugin action build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Package download
      run: sudo apt-get --assume-yes install libmpg123-dev zip gzip tar
    - name: make
      run: make && mkdir binary && make install PREFIX=./binary
    - name: make (debug)
      run: make clean && make DEBUG=1 && mkdir binary_debug && make install PREFIX=./binary_debug
    - uses: actions/upload-artifact@v1
      with:
        name: x86_64-binary-${{ github.sha }}
        path: ./binary
    - uses: actions/upload-artifact@v1
      with:
        name: DEBUG-x86_64-binary-${{ github.sha }}
        path: ./binary_debug


